language: android
sudo: required
jdk: oraclejdk8
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
android:
  components:
    - tools
    - platform-tools
    # https://developer.android.com/studio/releases/build-tools
    - build-tools
env:
  global:
    - NODE_VERSION=8
    - ANDROID_BUILD_TOOLS=28.0.3
    - ANDROID_PLATFORM=android-28
    - CC=gcc-6 CXX=g++-6
before_install:
  - echo y | android update sdk --no-ui -t tools
  - echo yes | sdkmanager tools > /dev/null
  - echo yes | sdkmanager --update > /dev/null
  - echo yes | sdkmanager "platforms;${ANDROID_PLATFORM}" > /dev/null
  - echo yes | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  - echo yes | sdkmanager "extras;android;m2repository" > /dev/null
  - echo yes | sdkmanager "extras;google;m2repository" > /dev/null
  - sdkmanager --list
install:
  # node stuff
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install ${NODE_VERSION}
  - node --version
  - npm --version

  # npm stuff
  - npm install
script:
  - npm run lint
  - npm run build
