parameters:
  name: ''
  task: ''
  jdk: ''


jobs:
- job: ${{ parameters.name }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(DEFAULT_NODE_VERSION)"
  - script: npm install
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: "${{ parameters.jdk }}"
      jdkArchitectureOption: 'x64'
      tasks: "${{ parameters.task }}"
