parameters:
  name: ''
  task: ''
  jdk: ''


jobs:
- job: ${{ parameters.name }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(DEFAULT_NODE_VERSION)"
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "${{ parameters.jdk }}"
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - script: npm install
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: "1.${{ parameters.jdk }}"
      jdkArchitectureOption: 'x64'
      tasks: "${{ parameters.task }}"
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactStagingDirectory)'
    inputs:
      Contents: '**/apks/*.apk'
      TargetFolder: '$(Build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: BuildApkOutputs
